### ISSUE TITLE
ValueError: Dependency on app with no migrations: users

### ISSUE THREAD

**Issue by ivan-vilches** [shamspias/customizable-gpt-chatbot#23]
Still trying this is my .env
```
ENV_NAME='local'

# TEMPORARY SECRET - DO NOT USE THIS
DJANGO_SETTINGS_MODULE=config.settings.local
DJANGO_SECRET_KEY='django-insecure-z#p-sa90q*k(n9xh632k@rgo=sd3@589=(%l8xpn=c-+yr&q=0'
DJANGO_DEBUG=True

# Database
DB_NAME=dbname
DB_USER=mysuer
DB_PASSWORD=mypass
DB_HOST=localhost
DB_PORT=5432

# Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# Email
EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
EMAIL_HOST=''
EMAIL_PORT=587
EMAIL_FROM=""

SITE_URL=http://localhost:8000
SITE_ID=1


# CORS
CSRF_COOKIE_SECURE=True
SESSION_COOKIE_SECURE=True
CSRF_COOKIE_HTTPONLY=False
SESSION_COOKIE_HTTPONLY=True
SESSION_COOKIE_SAMESITE="None"
CSRF_COOKIE_SAMESITE="None"
CORS_ALLOW_CREDENTIALS=True
CORS_ORIGIN_ALLOW_ALL=False
CSRF_COOKIE_NAME="csrftoken"
CORS_ALLOWED_ORIGINS=http://127.0.0.1:3000,http://localhost:3000
CSRF_TRUSTED_ORIGINS=http://127.0.0.1:3000,http://localhost:3000

# Security

X_FRAME_OPTIONS='DENY'
SECURE_BROWSER_XSS_FILTER=True

# GENERALS
AUTH_USER_MODEL=users.CustomUser
LANGUAGE_CODE="en-us"
APPEND_SLASH=True
TIME_ZONE='UTC'
USE_I18N=True
USE_TZ=True
USE_L10N=True

# Social
FACEBOOK_KEY=''
FACEBOOK_SECRET=''
GOOGLE_KEY=''
GOOGLE_SECRET=''

# Other API
OPEN_AI_KEY='sk-****************************************'
PINECONE_API_KEY='****************************************'
PINECONE_ENVIRONMENT='asia-northeast1-gcp'
PINECONE_INDEX_NAME='customchat'
PINECONE_NAMESPACE_NAME=''
SENTRY_DSN=''

# AWS
AWS_ACCESS_KEY=''
AWS_SECRET_KEY=''
REGION_NAME=''
QUEUE_NAME=''

DJANGO_AWS_STORAGE_BUCKET_NAME=''


# Admin Site Config
ADMIN_SITE_HEADER="Chatbot"
ADMIN_SITE_TITLE="Chatbot Dashboard"
ADMIN_SITE_INDEX="Chatbot Dashboard"

# RASA

RASA_API_URL = "http://localhost:5005/model/parse"

# OAuth2 settings
APPLICATION_NAME = "Chatbot"


LOGIN_REDIRECT_URL = "/"
```

```
when i run celery:
(venv) ivanvilches@MacBook-Air-de-Ivan customizable-gpt-chatbox-v2 % celery -A config worker --loglevel=info
 
 -------------- celery@MacBook-Air-de-Ivan.local v5.2.7 (dawn-chorus)
--- ***** ----- 
-- ******* ---- macOS-12.4-arm64-arm-64bit 2023-04-21 19:30:41
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         customize_chatgpt:0x106402510
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . chatbot.tasks.generate_title_request
  . chatbot.tasks.send_gpt_request
  . users.tasks.send_forgot_password_email

[2023-04-21 19:30:42,183: INFO/MainProcess] Connected to redis://localhost:6379/0
[2023-04-21 19:30:42,185: INFO/MainProcess] mingle: searching for neighbors
[2023-04-21 19:30:43,196: INFO/MainProcess] mingle: all alone
[2023-04-21 19:30:43,217: WARNING/MainProcess] /Users/ivanvilches/Documents/proyectos/AI/customizable-gpt-chatbox-v2/venv/lib/python3.11/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2023-04-21 19:30:43,217: INFO/MainProcess] celery@MacBook-Air-de-Ivan.local ready.
s
```

when i run:
mes@MacBook-Air-de-Ivan customizable-gpt-chatbox-v2 % source venv/bin/activate
(venv) me@MacBook-Air-de-Ivan customizable-gpt-chatbox-v2 % python manage.py runserver
INFO Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/ivanvilches/Documents/proyectos/AI/customizable-gpt-chatbox-v2/venv/lib/python3.11/site-packages/django/db/migrations/loader.py", line 187, in check_key
    return self.graph.root_nodes(key[0])[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ivanvilches/Documents/proyectos/AI/customizable-gpt-chatbox-v2/venv/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/ivanvilches/Documents/proyectos/AI/customizable-gpt-chatbox-v2/venv/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 136, in inner_run
    self.check_migrations()
  File "/Users/ivanvilches/Documents/proyectos/AI/customizable-gpt-chatbox-v2/venv/lib/python3.11/site-packages/django/core/management/base.py", line 574, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivanvilches/Documents/proyectos/AI/customizable-gpt-chatbox-v2/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivanvilches/Documents/proyectos/AI/customizable-gpt-chatbox-v2/venv/lib/python3.11/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/Users/ivanvilches/Documents/proyectos/AI/customizable-gpt-chatbox-v2/venv/lib/python3.11/site-packages/django/db/migrations/loader.py", line 250, in build_graph
    self.add_external_dependencies(key, migration)
  File "/Users/ivanvilches/Documents/proyectos/AI/customizable-gpt-chatbox-v2/venv/lib/python3.11/site-packages/django/db/migrations/loader.py", line 214, in add_external_dependencies
    parent = self.check_key(parent, key[0])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivanvilches/Documents/proyectos/AI/customizable-gpt-chatbox-v2/venv/lib/python3.11/site-packages/django/db/migrations/loader.py", line 194, in check_key
    raise ValueError(
ValueError: Dependency on app with no migrations: users

**Comment by ivan-vilches** [comment]
i solved with :
python3 manage.py makemigrations users
python manage.py migrate
then i 
 python3 manage.py runserver 
and in http://127.0.0.1:8000/ i only can see swagger stuff .
There is no ui or chat yet?
Thanks you
