### ISSUE TITLE
Mac m1 install fails.

### ISSUE THREAD

**Issue by urbanscribe** [shamspias/customizable-gpt-chatbot#25]
debug if helpful 

The error you're encountering seems to be due to Django not being able to find the 'User' model in the 'users' app. The error message AUTH_USER_MODEL refers to model 'users.User' that has not been installed suggests that Django is looking for a User model in an application named 'users', but cannot find it.

However, from the installation instructions you've followed, there doesn't seem to be any specific configuration related to the 'users' app or the User model:

Clone the repository: git clone https://github.com/shamspias/customizable-gpt-chatbot
Install the required packages: pip install -r requirements.txt
Run celery: celery -A config worker --loglevel=info
Run the Django server: python manage.py runserver
Open http://127.0.0.1:8000/ in your browser​0git clone [https://github.com/shamspias/customizable-gpt-chatbot`\n](https://github.com/shamspias/customizable-gpt-chatbot%60%5Cn) * Install the required packages by running pip install -r requirements.txt\n * Run celery celery -A config worker --loglevel=info\n * Run the command python manage.py runserver\n * Open http://127.0.0.1:8000/ in your browser\n\nIn linux and mac need to install 'sudo apt install python3-dev -y","pub_date":null}}`​.
Additional instructions for Linux and Mac installations involve the installation of development libraries for libcurl and the latest versions of pip and setuptools, and the installation of pycurl​0sudo apt-get install libcurl4-openssl-dev gcc libssl-dev -y\n 2. Make sure that you have the latest version of pip and setuptools installed by running the following command: pip install --upgrade pip setuptools\n 3. pip install pycurl","pub_date":null}}`​.

These instructions don't mention the creation or configuration of a 'users' app or a User model. If these are required for the project, they might be missing from the instructions or from the codebase itself.

Here are a few suggestions to troubleshoot this issue:

Check the Django settings: Django uses the AUTH_USER_MODEL setting in the settings.py file to determine which model to use for authentication. It should be in the format AppName.ModelName. If you have access to the codebase, verify that AUTH_USER_MODEL is set correctly.

Check the 'users' app: If the AUTH_USER_MODEL is set to 'users.User', verify that there is a 'users' app in the project and it contains a User model. If the 'users' app doesn't exist, you need to create it and define a User model in it. If the 'users' app exists but doesn't contain a User model, you need to create one.

Check the installed apps: In the settings.py file, there should be a list of installed apps (INSTALLED_APPS). Verify that 'users' is included in this list.

Check the database migrations: Django uses database migrations to create database tables corresponding to your models. If the 'users' app and User model exist but the corresponding database table doesn't, you might need to create a migration and apply it using the python manage.py makemigrations users and python manage.py migrate users commands.

If none of these suggestions work, there might be an issue with the codebase itself, and you might need to contact the maintainers of the project for further assistance.

**Comment by urbanscribe** [comment]
celery -A config worker --loglevel=info
Traceback (most recent call last):
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/django/apps/config.py", line 235, in get_model
    return self.models[model_name.lower()]
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 170, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL, require_ready=False)
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/django/apps/registry.py", line 213, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/django/apps/config.py", line 237, in get_model
    raise LookupError(
LookupError: App 'users' doesn't have a 'User' model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexfuchs/opt/anaconda3/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/celery/bin/celery.py", line 217, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/celery/bin/worker.py", line 343, in worker
    worker = app.Worker(
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/celery/worker/worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/celery/loaders/base.py", line 111, in init_worker
    self.import_default_modules()
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/celery/loaders/base.py", line 105, in import_default_modules
    raise response
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/celery/fixups/django.py", line 82, in on_import_modules
    self.worker_fixup.validate_models()
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/celery/fixups/django.py", line 120, in validate_models
    self.django_setup()
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/celery/fixups/django.py", line 116, in django_setup
    django.setup()
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/django/contrib/admin/__init__.py", line 50, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/django/contrib/auth/admin.py", line 6, in <module>
    from django.contrib.auth.forms import (
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/django/contrib/auth/forms.py", line 18, in <module>
    UserModel = get_user_model()
  File "/Users/alexfuchs/opt/anaconda3/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 176, in get_user_model
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'users.User' that has not been installed

**Comment by shamspias** [comment]
please make an .env file and keep updated information as your need.
